app1/urls.py
from django.urls import path
from app1.views import *
app_name='ganendra'

urlpatterns=[
    path('muni/',muni,name='muni'),
    path('venkey/',venkey,name='venkey'),

]

app2/urls.py
from django.urls import path
from app2.views import *
app_name='nagaram'

urlpatterns=[
    path('muni/',muni,name='muni'),
    path('venkey/',venkey,name='venkey'),
]

project8/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def muni(request):
    return render(request,'muni.html')

def venkey(request):
    return render(request,'venkey.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def muni(request):
    return render(request,'muni.html')

def venkey(request):
    return render(request,'venkey.html')

templates/muni.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>he is good boy</h1>
    <a href="{% url 'ganendra:venkey' %}">click link</a>
</body>
</html>

templates/venkey.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1> he is bad boy</h1>
    <a href="{% url 'nagaram:muni' %}">click link</a>
</body>
</html>